version: '3'
services:
  mslabel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    container_name: mslabel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/api
    volumes:
      - ./:/var/www/api
      - ./docker/php/php.ini:/etc/php.ini
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/sites-enabled/default
    ports:
      - "8090:80"
    extra_hosts:
      - "dev-api.xn--oi2b31he2e32g.xn--3e0b707e:127.0.0.1"
volumes:
  lbdata:
    driver: local